# Web Scraping Lecture Part 2 --- JSON APIs

## Content
5. Interacting with JSON APIs
6. Interacting with other type of APIs
7. Preparing for Project : Job Data Scraping

# 5. Interacting with JSON API


## What is API?

API stands for “Application Programming Interface.” It is an interface or communication protocol between a client and a server intended to simplify the building of client-side software. It has been described as a “contract” between the client and the server, such that if the client makes a request in a specific format, it will always get a response in a specific format or initiate a defined action. An API may be for a web-based system, operating system, database system, computer hardware, or software library.(Wiki)

Many websites have public APIs providing data feeds via JSON or some other formats. 

## JSON Data Introduction

JSON short for JavaScript Object Notation, has become one of the standard formats for sending data by HTTP request between web browers and other applications. It is a much more free-form data format than a tabular text form like CSV. 

For exmaple, this website shows the last 30 GitHub issues for pandas, https://api.github.com/repos/pandas-dev/pandas/issues. We call it is an API, and the data format is in JSON. Most web APIs return to JSON or xml format. 

Another example of JSON:

    {"ticker":"AAPL:US","return_code":0,"ttl":300,"disp_name":"Apple Inc","last_price":222.11,"price_precision":3.0,"time_of_last_updt":"2018-10-12","pct_chge_1D":3.57192993}

It is a much more free-form data format than a tabular text form like CSV. 

Sometimes people see json as nested dictionary in python. 

**json library**

There are several python libraries for reading and writing JSON data. *json* is one of those. To convert a JSON string to Python form, we use *json.loads*.

In [5]:
#Define a json string. 
obj="""
{"name":"Wes",
 "places_lived":["United States","Spain","China"],
 "siblings":[{"name":"Scott","age":30,"pets":["Zeus","Zuko"]},
             {"name":"Katie","age":38,"pets":["Sixes","Cisco"]}]
}
"""
obj

'\n{"name":"Wes",\n "places_lived":["United States","Spain","China"],\n "siblings":[{"name":"Scott","age":30,"pets":["Zeus","Zuko"]},\n             {"name":"Katie","age":38,"pets":["Sixes","Cisco"]}]\n}\n'

In [6]:
import json
result=json.loads(obj) # json.loads() convert a json string to python dictionary.
result
#result can be treated as a dictionary in python.

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'China'],
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Cisco']}]}

In [7]:
result['siblings']

[{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
 {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Cisco']}]

In [8]:
result['siblings'][0]

{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']}

In [9]:
result['siblings'][0]['pets']

['Zeus', 'Zuko']

In [10]:
result['siblings'][0]['pets'][0]

'Zeus'

In [11]:
#converts a python object back to JSON string. 
asjon=json.dumps(result)
asjon

'{"name": "Wes", "places_lived": ["United States", "Spain", "China"], "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Cisco"]}]}'

In [12]:
import pandas as pd
siblings=pd.DataFrame(result['places_lived'])
siblings

               0
0  United States
1          Spain
2          China

In [13]:
siblings=pd.DataFrame(result["siblings"])
siblings

    name  age            pets
0  Scott   30    [Zeus, Zuko]
1  Katie   38  [Sixes, Cisco]

In [14]:
siblings=pd.DataFrame(result["siblings"][0])
siblings

    name  age  pets
0  Scott   30  Zeus
1  Scott   30  Zuko

In [15]:
siblings=pd.DataFrame(result["siblings"][0]['pets'])
siblings

      0
0  Zeus
1  Zuko

## <font color='red'>**Exercise: Access the nested key ‘salary’ from the following JSON**</font>

write code to print the value of salary

expected output: 

7000

In [16]:
import json

sampleJson = """{ 
   "company":{ 
      "employee":{ 
         "name":"emma",
         "payble":{ 
            "salary":7000,
            "bonus":800
         }
      }
   }
}"""

## <font color='red'>**Exercise:**</font>
Parse the following JSON to get all the values of a key ‘name’ within an array

Expected output:

["name1", "name2"]

In [17]:
[ 
   { 
      "id":1,
      "name":"name1",
      "color":[ 
         "red",
         "green"
      ]
   },
   { 
      "id":2,
      "name":"name2",
      "color":[ 
         "pink",
         "yellow"
      ]
   }
]

[{'id': 1, 'name': 'name1', 'color': ['red', 'green']},
 {'id': 2, 'name': 'name2', 'color': ['pink', 'yellow']}]

## Scraping JSON using requests lib
One easy-to-use method to access APIs from python is the **requests** package. The requests library will make a **GET** request to a web server, which will download the HTML contents of a given web page for us. There are several different types of requests we can make using requests, of which GET is just one.

To find the last 30 GitHub issues for pandas on GitHub, we make a **GET HTTP** request.

In [18]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
resp=requests.get(url)#When you ping a website or portal for information this is called making a request. 
                       #That is exactly what the Requests library has been designed to do.
resp # resp is a Response object.

After running our request, we get a Response object. This object has a status_code property, which indicates if the page was downloaded successfully. 

A status_code of 200 means that the page downloaded successfully. We won’t fully dive into status codes here, but a status code starting with a 2 generally indicates success, and a code starting with a 4 or a 5 indicates an error.

In [19]:
data=resp.json()# Response object's json method will return to a dictionary 
                # containing JSON parsed into native python objects. 
len(data)
# each element in data is a dictionary containing all the data found on a GitHub issue page.

30

In [20]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
  'id': 2942576054,
  'node_id': 'PR_kwDOAA0YD86P1abm',
  'number': 61173,
  'title': 'BUG: Handle line and bar on the same plot',
  'user': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-24T09:22:19Z',
  'updated_at': '2025-03-24T10:51:17Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61173',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61173.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61173.patch',
   'merged_at': None},
  'body': "- [x] closes #61161\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\nPlease provide feedback on the overall approach. Once confirmed, I'll expand and cover with tests.\r\n",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61172',
  'id': 2941851698,
  'node_id': 'I_kwDOAA0YD86vWRgy',
  'number': 61172,
  'title': 'BUG: pd.read_csv() on empty files should give an empty dataframe pd.DataFrame()',
  'user': {'login': 'xuancong84',
   'id': 10172392,
   'node_id': 'MDQ6VXNlcjEwMTcyMzky',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10172392?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/xuancong84',
   'html_url': 'https://github.com/xuancong84',
   'followers_url': 'https://api.github.com/users/xuancong84/followers',
   'following_url': 'https://api.github.com/users/xuancong84/following{/other_user}',
   'gists_url': 'https://api.github.com/users/xuancong84/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/xuancong84/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/xuancong84/subscriptions',
   'organizations_url': 'https://api.github.com/users/xuancong84/orgs',
   'repos_url': 'https://api.github.com/users/xuancong84/repos',
   'events_url': 'https://api.github.com/users/xuancong84/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/xuancong84/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv'},
   {'id': 2365504893,
    'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate',
    'name': 'Closing Candidate',
    'color': 'be21f2',
    'default': False,
    'description': 'May be closeable, needs more eyeballs'}],
  'state': 'open',
  'locked': False,
  'assignee': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'assignees': [{'login': 'MartinBraquet',
    'id': 25173236,
    'node_id': 'MDQ6VXNlcjI1MTczMjM2',
    'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/MartinBraquet',
    'html_url': 'https://github.com/MartinBraquet',
    'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
    'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
    'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
    'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
    'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
    'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False}],
  'milestone': None,
  'comments': 3,
  'created_at': '2025-03-24T03:07:45Z',
  'updated_at': '2025-03-24T20:51:16Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [x] I have checked that this issue has not already been reported.\n\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nUsing `pd.read_csv()` to open an empty CSV file (0-bytes file or single-byte file (EOL character) by VIM) will give the following error:\n\nTraceback (most recent call last):\n  File "<stdin>", line 1, in <module>\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine\n    return mapping[engine](f, **self.options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__\npandas.errors.EmptyDataError: No columns to parse from file\n```\n\n### Issue Description\n\nThe reason of the crash is that there is no columns to parse. However, Pandas does allow dataframes with no columns and no rows, i.e., `pd.DataFrame()` gives an empty DataFrame with no rows and no columns.\n\nThe logic reasoning is that if opening an empty CSV will cause crash, then **opening what kind of CSV file will give rise to an empty DataFrame**? When designing APIs, one fundamental principle is to try to keep a 1-to-1 mapping between input and output (so as to reduce information loss); thus, in this case, it is the mapping between CSV file and dataframe. I do agree that if the CSV does not exist or cannot be read (due to permission), then the call should crash. But if the CSV file is empty, `pd.read_csv()` should give an empty dataframe because empty dataframe does exist. Otherwise, what text should I put into a CSV file so that `pd.read_csv()` will give an empty DataFrame, i.e., `pd.DataFrame()`? Thanks!\n\n### Expected Behavior\n\nOpening an empty CSV file should give an empty DataFrame (i.e., pd.DataFrame()):\n```\nEmpty DataFrame\nColumns: []\nIndex: []\n```\n\n### Installed Versions\n\n<details>\n\nINSTALLED VERSIONS\n------------------\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\npython                : 3.11.5\npython-bits           : 64\nOS                    : Linux\nOS-release            : 6.8.0-52-generic\nVersion               : #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2\nmachine               : x86_64\nprocessor             : x86_64\nbyteorder             : little\nLC_ALL                : en_US.UTF-8\nLANG                  : en_US.UTF-8\nLOCALE                : en_US.UTF-8\n\npandas                : 2.2.3\nnumpy                 : 1.26.4\npytz                  : 2023.3.post1\ndateutil              : 2.8.2\npip                   : 25.0.1\nCython                : None\nsphinx                : 5.0.2\nIPython               : 8.15.0\nadbc-driver-postgresql: None\nadbc-driver-sqlite    : None\nbs4                   : 4.12.2\nblosc                 : None\nbottleneck            : 1.4.0\ndataframe-api-compat  : None\nfastparquet           : None\nfsspec                : 2025.2.0\nhtml5lib              : None\nhypothesis            : None\ngcsfs                 : None\njinja2                : 3.1.2\nlxml.etree            : 4.9.3\nmatplotlib            : 3.8.4\nnumba                 : 0.60.0\nnumexpr               : 2.8.4\nodfpy                 : None\nopenpyxl              : None\npandas_gbq            : None\npsycopg2              : None\npymysql               : None\npyarrow               : 11.0.0\npyreadstat            : None\npytest                : 7.4.0\npython-calamine       : None\npyxlsb                : None\ns3fs                  : None\nscipy                 : 1.14.1\nsqlalchemy            : None\ntables                : 3.9.2\ntabulate              : None\nxarray                : 2023.6.0\nxlrd                  : None\nxlsxwriter            : 3.2.2\nzstandard             : 0.19.0\ntzdata                : 2023.3\nqtpy                  : None\npyqt5                 : None\n\n\n</details>\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
  'id': 2941462140,
  'node_id': 'PR_kwDOAA0YD86Pxsxt',
  'number': 61171,
  'title': 'DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',
   'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-23T20:16:22Z',
  'updated_at': '2025-03-24T20:06:28Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61171',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61171.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61171.patch',
   'merged_at': None},
  'body': '- [ ] closes #61170  (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61170',
  'id': 2941455212,
  'node_id': 'I_kwDOAA0YD86vUwts',
  'number': 61170,
  'title': 'BUG: DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',
   'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 49379259,
    'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON',
    'name': 'IO JSON',
    'color': '207de5',
    'default': False,
    'description': 'read_json, to_json, json_normalize'}],
  'state': 'open',
  'locked': False,
  'assignee': {'login': 'GalkaKG',
   'id': 103485495,
   'node_id': 'U_kgDOBisQNw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/103485495?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/GalkaKG',
   'html_url': 'https://github.com/GalkaKG',

## Scraping JSON using urllib lib

Please find the last 30 GitHub issues for pandas on GitHub.

In [21]:
from urllib.request import urlopen
import json
url='https://api.github.com/repos/pandas-dev/pandas/issues'
htmlfile = urlopen(url)
htmltext=htmlfile.read() #htmltext is a json string object
data = json.loads(htmltext) #json.loads() method convert a json string to a list of Python dictionaries. 
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
  'id': 2942576054,
  'node_id': 'PR_kwDOAA0YD86P1abm',
  'number': 61173,
  'title': 'BUG: Handle line and bar on the same plot',
  'user': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-24T09:22:19Z',
  'updated_at': '2025-03-24T10:51:17Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61173',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61173.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61173.patch',
   'merged_at': None},
  'body': "- [x] closes #61161\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\nPlease provide feedback on the overall approach. Once confirmed, I'll expand and cover with tests.\r\n",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61172',
  'id': 2941851698,
  'node_id': 'I_kwDOAA0YD86vWRgy',
  'number': 61172,
  'title': 'BUG: pd.read_csv() on empty files should give an empty dataframe pd.DataFrame()',
  'user': {'login': 'xuancong84',
   'id': 10172392,
   'node_id': 'MDQ6VXNlcjEwMTcyMzky',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10172392?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/xuancong84',
   'html_url': 'https://github.com/xuancong84',
   'followers_url': 'https://api.github.com/users/xuancong84/followers',
   'following_url': 'https://api.github.com/users/xuancong84/following{/other_user}',
   'gists_url': 'https://api.github.com/users/xuancong84/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/xuancong84/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/xuancong84/subscriptions',
   'organizations_url': 'https://api.github.com/users/xuancong84/orgs',
   'repos_url': 'https://api.github.com/users/xuancong84/repos',
   'events_url': 'https://api.github.com/users/xuancong84/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/xuancong84/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv'},
   {'id': 2365504893,
    'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate',
    'name': 'Closing Candidate',
    'color': 'be21f2',
    'default': False,
    'description': 'May be closeable, needs more eyeballs'}],
  'state': 'open',
  'locked': False,
  'assignee': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'assignees': [{'login': 'MartinBraquet',
    'id': 25173236,
    'node_id': 'MDQ6VXNlcjI1MTczMjM2',
    'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/MartinBraquet',
    'html_url': 'https://github.com/MartinBraquet',
    'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
    'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
    'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
    'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
    'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
    'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False}],
  'milestone': None,
  'comments': 3,
  'created_at': '2025-03-24T03:07:45Z',
  'updated_at': '2025-03-24T20:51:16Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [x] I have checked that this issue has not already been reported.\n\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nUsing `pd.read_csv()` to open an empty CSV file (0-bytes file or single-byte file (EOL character) by VIM) will give the following error:\n\nTraceback (most recent call last):\n  File "<stdin>", line 1, in <module>\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine\n    return mapping[engine](f, **self.options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__\npandas.errors.EmptyDataError: No columns to parse from file\n```\n\n### Issue Description\n\nThe reason of the crash is that there is no columns to parse. However, Pandas does allow dataframes with no columns and no rows, i.e., `pd.DataFrame()` gives an empty DataFrame with no rows and no columns.\n\nThe logic reasoning is that if opening an empty CSV will cause crash, then **opening what kind of CSV file will give rise to an empty DataFrame**? When designing APIs, one fundamental principle is to try to keep a 1-to-1 mapping between input and output (so as to reduce information loss); thus, in this case, it is the mapping between CSV file and dataframe. I do agree that if the CSV does not exist or cannot be read (due to permission), then the call should crash. But if the CSV file is empty, `pd.read_csv()` should give an empty dataframe because empty dataframe does exist. Otherwise, what text should I put into a CSV file so that `pd.read_csv()` will give an empty DataFrame, i.e., `pd.DataFrame()`? Thanks!\n\n### Expected Behavior\n\nOpening an empty CSV file should give an empty DataFrame (i.e., pd.DataFrame()):\n```\nEmpty DataFrame\nColumns: []\nIndex: []\n```\n\n### Installed Versions\n\n<details>\n\nINSTALLED VERSIONS\n------------------\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\npython                : 3.11.5\npython-bits           : 64\nOS                    : Linux\nOS-release            : 6.8.0-52-generic\nVersion               : #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2\nmachine               : x86_64\nprocessor             : x86_64\nbyteorder             : little\nLC_ALL                : en_US.UTF-8\nLANG                  : en_US.UTF-8\nLOCALE                : en_US.UTF-8\n\npandas                : 2.2.3\nnumpy                 : 1.26.4\npytz                  : 2023.3.post1\ndateutil              : 2.8.2\npip                   : 25.0.1\nCython                : None\nsphinx                : 5.0.2\nIPython               : 8.15.0\nadbc-driver-postgresql: None\nadbc-driver-sqlite    : None\nbs4                   : 4.12.2\nblosc                 : None\nbottleneck            : 1.4.0\ndataframe-api-compat  : None\nfastparquet           : None\nfsspec                : 2025.2.0\nhtml5lib              : None\nhypothesis            : None\ngcsfs                 : None\njinja2                : 3.1.2\nlxml.etree            : 4.9.3\nmatplotlib            : 3.8.4\nnumba                 : 0.60.0\nnumexpr               : 2.8.4\nodfpy                 : None\nopenpyxl              : None\npandas_gbq            : None\npsycopg2              : None\npymysql               : None\npyarrow               : 11.0.0\npyreadstat            : None\npytest                : 7.4.0\npython-calamine       : None\npyxlsb                : None\ns3fs                  : None\nscipy                 : 1.14.1\nsqlalchemy            : None\ntables                : 3.9.2\ntabulate              : None\nxarray                : 2023.6.0\nxlrd                  : None\nxlsxwriter            : 3.2.2\nzstandard             : 0.19.0\ntzdata                : 2023.3\nqtpy                  : None\npyqt5                 : None\n\n\n</details>\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
  'id': 2941462140,
  'node_id': 'PR_kwDOAA0YD86Pxsxt',
  'number': 61171,
  'title': 'DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',
   'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-23T20:16:22Z',
  'updated_at': '2025-03-24T20:06:28Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61171',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61171.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61171.patch',
   'merged_at': None},
  'body': '- [ ] closes #61170  (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61170',
  'id': 2941455212,
  'node_id': 'I_kwDOAA0YD86vUwts',
  'number': 61170,
  'title': 'BUG: DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',
   'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 49379259,
    'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON',
    'name': 'IO JSON',
    'color': '207de5',
    'default': False,
    'description': 'read_json, to_json, json_normalize'}],
  'state': 'open',
  'locked': False,
  'assignee': {'login': 'GalkaKG',
   'id': 103485495,
   'node_id': 'U_kgDOBisQNw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/103485495?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/GalkaKG',
   'html_url': 'https://github.com/GalkaKG',

**<font color='red'>Exercise</font>**

Can you name a few common keywords and convert data to a DataFrame that contains the value of those keywords? Howe many rows does it have?

In [22]:

issues=pd.DataFrame(data,columns=['number','title','labels','state', 'created_at'])
issues

,number,title,labels,state,created_at
0,61173,BUG: Handle line and bar on the same plot,[],open,2025-03-24T09:22:19Z
1,61172,BUG: pd.read_csv() on empty files should give ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-24T03:07:45Z
2,61171,DataFrame.dtypes.to_json OverflowError: Maximu...,[],open,2025-03-23T20:16:22Z
3,61170,BUG: DataFrame.dtypes.to_json OverflowError: M...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-23T20:08:19Z
4,61168,ENH: Accept no fields for groupby by,[],open,2025-03-23T13:21:20Z
5,61166,ENH: Enable nsmallest/nlargest on object dtype,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2025-03-22T10:36:03Z
6,61164,ENH: merge_asof threshold minimum,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2025-03-21T21:26:28Z
7,61163,"WEB: Remove self (Marco Gorelli) from ""active ...","[{'id': 1508144531, 'node_id': 'MDU6TGFiZWwxNT...",open,2025-03-21T20:24:14Z
8,61162,ENH: Support boolean masks for `iloc.__getitem__`,[],open,2025-03-21T19:44:44Z
9,61161,BUG: fails to plot 2 plots with secondary y ax...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-21T19:34:07Z
10,61160,ENH: Accept no fields for groupby by,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2025-03-21T18:19:54Z
11,61157,Csv func,[],open,2025-03-20T20:41:52Z
12,61156,BUILD: Cython.Compiler.Errors: 'free_threading...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open,2025-03-20T17:59:23Z
13,61155,BUG: Impossible creation of array with dtype=s...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-20T14:25:51Z
14,61154,BUG: Clip corr edge cases between -1.0 and 1.0,"[{'id': 5331296438, 'node_id': 'LA_kwDOAA0YD88...",open,2025-03-20T13:15:41Z
15,61153,BUG: import pandas 2.2.3 on WSL 2.4.12.0 raise...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-20T10:12:53Z
16,61152,ENH: Adds `dict` & `**dict` support for `pd.se...,[],open,2025-03-20T07:07:50Z
17,61151,ENH: Added dict support for `pd.set_option`,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2025-03-20T05:38:08Z
18,61149,BUG: Added deprecation warning to Timestamp co...,[],open,2025-03-20T01:42:57Z
19,61148,String dtype: more informative repr (keeping b...,"[{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEw...",open,2025-03-19T18:35:07Z
20,61145,BUG: Inconsistent index type when using read_c...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-19T08:56:21Z
21,61144,BUG(?): rolling sum with pyarrow types results...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-18T15:28:39Z
22,61143,Preserve column names in empty Dataframe,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-18T15:25:23Z
23,61142,BUG: Collision between equivalent frequencies ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-18T13:54:49Z
24,61140,BUG: `DataFrame.from_records()` ignores `colum...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2025-03-17T18:13:09Z
25,61138,API (string dtype): implement hierarchy (NA > ...,"[{'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIy...",open,2025-03-17T10:08:28Z
26,61128,Improve the apply/map APIs,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open,2025-03-15T05:13:02Z
27,61126,DOC: Write user guide page on apply/map/transf...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open,2025-03-15T04:03:22Z
28,61125,ENH: Supporting third-party engines for all `m...,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open,2025-03-15T03:21:13Z
29,61124,ENH: fillna enhancement with method='nearest',"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2025-03-15T01:03:57Z

## Another Example

In [ ]:
response = requests.get("https://jsonplaceholder.typicode.com/todos")
todos = json.loads(response.text)

In [ ]:
todos[:10]

In [ ]:
# Map of userId to number of complete TODOs for that user
todos_by_user = {}

# Increment complete TODOs count for each user.
for todo in todos:
    if todo["completed"]:
        try:
            # Increment the existing user's count.
            todos_by_user[todo["userId"]] += 1
        except KeyError:
            # This user has not been seen. Set their count to 1.
            todos_by_user[todo["userId"]] = 1

# Create a sorted list of (userId, num_complete) pairs.
top_users = sorted(todos_by_user.items(), 
                   key=lambda x: x[1], reverse=True)

# Get the maximum number of complete TODOs.
max_complete = top_users[0][1]

# Create a list of all users who have completed
# the maximum number of TODOs.
users = []
for user, num_complete in top_users:
    if num_complete < max_complete:
        break
    users.append(str(user))

max_users = " and ".join(users)

In [ ]:
s = "s" if len(users) > 1 else ""
print(f"user{s} {max_users} completed {max_complete} TODOs")